{% set name = "xpdAcq" %}
{% set version = "0.10.4" %}
{% set sha256 = "d338bbd18c4c628c65874db587f24c9ae664373c18d11b8c6985ea61b365c582" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ version  }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - ipython
    - numpy
    - ophyd
    - pandas
    - pyfai
    - pyyaml
    - xlrd
    - xpdan
    - xpdconf
    - xpdsim

test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtimeSetup

about:
  home: http://xpdacq.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python package that aids data acquisition at the NSLS-II XPD and PDF Beamline.
  dev_url: https://github.com/xpdAcq/xpdAcq
  doc_url: http://xpdacq.github.io/xpdAcq
