{% set version = "0.10.4" %}

package:
  name: xpdacq
  version: {{ version }}

source:
  git_url: https://github.com/xpdAcq/xpdAcq.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pyyaml
    - pandas
    - xlrd
    - pyfai
    - ipython
    - bluesky
    - xpdan
    - xpdsim
    - databroker
    - ophyd
    - xpdconf

test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtimeSetup

about:
  home: http://xpdacq.github.io/xpdAcq
  license_file: LICENSE
