{% set name = "xpdAcq" %}
{% set v = "0.11.0" %}
{% set sha256 = "befb9dbdb5fa32ff8a554ee49e238769154ca5d6891b4375f5115dedca50310e" %}

package:
  name: {{ name|lower }}
  version: {{ v }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ v }}/{{ name }}-{{ v }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - ipython
    - numpy
    - ophyd
    - pandas
    - pyfai
    - pyyaml
    - xlrd
    - xpdconf
    - xpdsim

test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtimeSetup

about:
  home: http://xpdacq.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Python package that aids data acquisition at the NSLS-II XPD and PDF Beamline.
  dev_url: https://github.com/xpdAcq/xpdAcq
  doc_url: http://xpdacq.github.io/xpdAcq
